# Generated by Django 3.0.7 on 2021-02-05 07:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trending',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
