# Generated by Django 3.0.7 on 2021-02-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210205_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_img', models.ImageField(upload_to='images/')),
                ('banner_title', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='trending',
            name='picture',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
