# Generated by Django 3.0.7 on 2021-02-15 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20210215_1622'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
