# Generated by Django 3.0.7 on 2021-02-16 07:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Latest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_img', models.ImageField(upload_to='images/')),
                ('banner_title', models.CharField(max_length=250)),
                ('description', ckeditor.fields.RichTextField()),
                ('small_desc', ckeditor.fields.RichTextField()),
                ('small_img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
